name: My-GitHubActions-Basics
env:
  APPLICATION_NAME    : "MyWordpress"
  DEPLOY_PACKAGE_NAME : "Wordpress-deploy-ver-${{ github.sha }}"

on: 
  push:
    branches: 
      - master

jobs:
  my_ci:
    runs-on: test

    steps:
    - name: Print Hello Message in Testing
      run : echo "Hello World from Testing job"
    
    - name: Execure few commands
      run : |
        echo "Hello Message"
        echo "Appication name: ${{ env.APPLICATION_NAME }}"
    
    - name: List current folder
      run : pwd
   
    - name: Git clone my repo
      uses: actions/checkout@v1   
          
  my_cd:
    runs-on: test
    needs: [my_ci]
#    if: github == 'refs/heads/master' && github.event_name == 'push' 
       
    steps:        
    - name: Printing Deployment package
      run : echo "Deploy pakcage name is ${{ env.DEPLOY_PACKAGE_NAME }}"
    
    - name: Deploy to server :)
      run : |
           pwd
           ls -la
           
  my_notification:
      runs-on: test
      needs: [my_cd]
       
      steps:        
      - name: Deploy notification
        run : curl -X POST https://api.telegram.org/bot${{ secrets.TOKEN }}/sendMessage -d "chat_id=1108837141" -d text="Deploy successful"
